# Generated by Django 3.1.7 on 2021-04-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('des', models.CharField(blank=True, max_length=400)),
                ('created', models.DateTimeField(auto_now=True)),
                ('see', models.SmallIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Youtube',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
