version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1382277156
    container_name: postgres_db








  #version: "3.8"
  #
  #services:
  #    django:
  #        build: .
  #        container_name: django
  #        command: python manage.py runserver 0.0.0.0:8000
  #        volumes:
  #            - .:/usr/src/app
  #        ports:
  #            - "8000:8000"
  #        depends_on:
  #            - pgdb
  #    pgdb:
  #
#  image: postgres
#        container_name: pgdb
#        environment:
#        - POSTGRES_DB=shop_db
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=1382277156